shp2json PA/1/districts.shp -o PA/1/districts.json
shp2json PA/2/districts.shp -o PA/2/districts.json
shp2json PA/3/districts.shp -o PA/3/districts.json
shp2json PA/4/districts.shp -o PA/4/districts.json
shp2json PA/5/districts.shp -o PA/5/districts.json
shp2json PA/6/districts.shp -o PA/6/districts.json
shp2json PA/7/districts.shp -o PA/7/districts.json
shp2json PA/8/districts.shp -o PA/8/districts.json
shp2json PA/9/districts.shp -o PA/9/districts.json
shp2json PA/10/districts.shp -o PA/10/districts.json
shp2json PA/11/districts.shp -o PA/11/districts.json
shp2json PA/12/districts.shp -o PA/12/districts.json
shp2json PA/13/districts.shp -o PA/13/districts.json
shp2json PA/14/districts.shp -o PA/14/districts.json
shp2json PA/15/districts.shp -o PA/15/districts.json
shp2json PA/16/districts.shp -o PA/16/districts.json
shp2json PA/17/districts.shp -o PA/17/districts.json
shp2json PA/18/districts.shp -o PA/18/districts.json
shp2json PA/19/districts.shp -o PA/19/districts.json
shp2json PA/20/districts.shp -o PA/20/districts.json
shp2json PA/21/districts.shp -o PA/21/districts.json
shp2json PA/22/districts.shp -o PA/22/districts.json
shp2json PA/23/districts.shp -o PA/23/districts.json
shp2json PA/24/districts.shp -o PA/24/districts.json
shp2json PA/25/districts.shp -o PA/25/districts.json
shp2json PA/26/districts.shp -o PA/26/districts.json
shp2json PA/27/districts.shp -o PA/27/districts.json
shp2json PA/28/districts.shp -o PA/28/districts.json
shp2json PA/29/districts.shp -o PA/29/districts.json
shp2json PA/30/districts.shp -o PA/30/districts.json
shp2json PA/31/districts.shp -o PA/31/districts.json
shp2json PA/32/districts.shp -o PA/32/districts.json
shp2json PA/33/districts.shp -o PA/33/districts.json
shp2json PA/34/districts.shp -o PA/34/districts.json
shp2json PA/35/districts.shp -o PA/35/districts.json
shp2json PA/36/districts.shp -o PA/36/districts.json
shp2json PA/37/districts.shp -o PA/37/districts.json
shp2json PA/38/districts.shp -o PA/38/districts.json
shp2json PA/39/districts.shp -o PA/39/districts.json
shp2json PA/40/districts.shp -o PA/40/districts.json
shp2json PA/41/districts.shp -o PA/41/districts.json
shp2json PA/42/districts.shp -o PA/42/districts.json
shp2json PA/43/districts.shp -o PA/43/districts.json
shp2json PA/44/districts.shp -o PA/44/districts.json
shp2json PA/45/districts.shp -o PA/45/districts.json
shp2json PA/46/districts.shp -o PA/46/districts.json
shp2json PA/47/districts.shp -o PA/47/districts.json
shp2json PA/48/districts.shp -o PA/48/districts.json
shp2json PA/49/districts.shp -o PA/49/districts.json
shp2json PA/50/districts.shp -o PA/50/districts.json
shp2json PA/51/districts.shp -o PA/51/districts.json
shp2json PA/52/districts.shp -o PA/52/districts.json
shp2json PA/53/districts.shp -o PA/53/districts.json
shp2json PA/54/districts.shp -o PA/54/districts.json
shp2json PA/55/districts.shp -o PA/55/districts.json
shp2json PA/56/districts.shp -o PA/56/districts.json
shp2json PA/57/districts.shp -o PA/57/districts.json
shp2json PA/58/districts.shp -o PA/58/districts.json
shp2json PA/59/districts.shp -o PA/59/districts.json
shp2json PA/60/districts.shp -o PA/60/districts.json
shp2json PA/61/districts.shp -o PA/61/districts.json
shp2json PA/62/districts.shp -o PA/62/districts.json
shp2json PA/63/districts.shp -o PA/63/districts.json
shp2json PA/64/districts.shp -o PA/64/districts.json
shp2json PA/65/districts.shp -o PA/65/districts.json
shp2json PA/66/districts.shp -o PA/66/districts.json
shp2json PA/67/districts.shp -o PA/67/districts.json
shp2json PA/68/districts.shp -o PA/68/districts.json
shp2json PA/69/districts.shp -o PA/69/districts.json
shp2json PA/70/districts.shp -o PA/70/districts.json
shp2json PA/71/districts.shp -o PA/71/districts.json
shp2json PA/72/districts.shp -o PA/72/districts.json
shp2json PA/73/districts.shp -o PA/73/districts.json
shp2json PA/74/districts.shp -o PA/74/districts.json
shp2json PA/75/districts.shp -o PA/75/districts.json
shp2json PA/76/districts.shp -o PA/76/districts.json
shp2json PA/77/districts.shp -o PA/77/districts.json
shp2json PA/78/districts.shp -o PA/78/districts.json
shp2json PA/79/districts.shp -o PA/79/districts.json
shp2json PA/80/districts.shp -o PA/80/districts.json
shp2json PA/81/districts.shp -o PA/81/districts.json
shp2json PA/82/districts.shp -o PA/82/districts.json
shp2json PA/83/districts.shp -o PA/83/districts.json
shp2json PA/84/districts.shp -o PA/84/districts.json
shp2json PA/85/districts.shp -o PA/85/districts.json
shp2json PA/86/districts.shp -o PA/86/districts.json
shp2json PA/87/districts.shp -o PA/87/districts.json
shp2json PA/88/districts.shp -o PA/88/districts.json
shp2json PA/89/districts.shp -o PA/89/districts.json
shp2json PA/90/districts.shp -o PA/90/districts.json
shp2json PA/91/districts.shp -o PA/91/districts.json
shp2json PA/92/districts.shp -o PA/92/districts.json
shp2json PA/93/districts.shp -o PA/93/districts.json
shp2json PA/94/districts.shp -o PA/94/districts.json
shp2json PA/95/districts.shp -o PA/95/districts.json
shp2json PA/96/districts.shp -o PA/96/districts.json
shp2json PA/97/districts.shp -o PA/97/districts.json
shp2json PA/98/districts.shp -o PA/98/districts.json
shp2json PA/99/districts.shp -o PA/99/districts.json
shp2json PA/100/districts.shp -o PA/100/districts.json